### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by mkhfring** [data301-2021-summer2/project-group16-data-301-project#1]
Hello, Group 16, 

My name is Mohamad Khajezade, and I will be giving you some feedback on your project. 

"This is a good starting point, but there is some work that needs to be done to elevate this project to our standards, so it meets our expectations."

I have divided up the feedback into several sections, so it is easier for you to implement.

## Task 1

Good job

## Task 2

- [1] All in all, task 2 was ok. Yet, I had to browse your repo to find where you have called your method changing.  
## Task 3

- [1 ] This task was not addressed correctly. For this task, you need to generated different charts to explain your data. You have used some pictures, which is not acceptable. 

## Task 4

- [1 ]  This task was not addressed as expected. You need to use different charts, and you need to create some reports using python in your notebook. Instead, you have to use some pictures, which is not acceptable.

**Comment by Bellinda12** [comment]
Hello Mohamad,

After speaking with Dr. Moosvi, we will add the links to out Jupyter Notebooks where we generated the graphs into our combined analysis file. We have only included the png of our graphs that were generated by our code to try to clean up the final analysis notebook so there isn't so much code. Sorry about this misunderstanding. Our graphs were all generated by us in the analysis files under our names.

Thank you.

**Comment by mkhfring** [comment]
Hello,

That's great. Please let me know when you added the chart. Then I can go ahead and change your feedbacks (with permission from Dr. Moosvi).

Cheers,
Mohamad

**Comment by Bellinda12** [comment]
Hello Mohamad,

We have added the links to our notebooks in the combined analysis. The generations of the graphs can be found in those documents.

Thank you.

**Comment by mkhfring** [comment]
Hello Bellinda,

Thanks for letting me know. I changed the feedbacks for your group on grade scope. 

Cheers,
Mohamad
